/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosPcvRouteImport } from './routes/usuarios-pcv'
import { Route as SerasaRouteImport } from './routes/serasa'
import { Route as RateiosRouteImport } from './routes/rateios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestoresLogonRouteImport } from './routes/gestores-logon'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RateiosIndexRouteImport } from './routes/rateios.index'
import { Route as SerasaProcessosRouteImport } from './routes/serasa.processos'
import { Route as SerasaEnvioRouteImport } from './routes/serasa.envio'
import { Route as SerasaDivisaoRouteImport } from './routes/serasa.divisao'
import { Route as RateiosNovoRouteImport } from './routes/rateios.novo'
import { Route as RateiosIdRouteImport } from './routes/rateios.$id'

const UsuariosPcvRoute = UsuariosPcvRouteImport.update({
  id: '/usuarios-pcv',
  path: '/usuarios-pcv',
  getParentRoute: () => rootRouteImport,
} as any)
const SerasaRoute = SerasaRouteImport.update({
  id: '/serasa',
  path: '/serasa',
  getParentRoute: () => rootRouteImport,
} as any)
const RateiosRoute = RateiosRouteImport.update({
  id: '/rateios',
  path: '/rateios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestoresLogonRoute = GestoresLogonRouteImport.update({
  id: '/gestores-logon',
  path: '/gestores-logon',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RateiosIndexRoute = RateiosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RateiosRoute,
} as any)
const SerasaProcessosRoute = SerasaProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => SerasaRoute,
} as any)
const SerasaEnvioRoute = SerasaEnvioRouteImport.update({
  id: '/envio',
  path: '/envio',
  getParentRoute: () => SerasaRoute,
} as any)
const SerasaDivisaoRoute = SerasaDivisaoRouteImport.update({
  id: '/divisao',
  path: '/divisao',
  getParentRoute: () => SerasaRoute,
} as any)
const RateiosNovoRoute = RateiosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => RateiosRoute,
} as any)
const RateiosIdRoute = RateiosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RateiosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/gestores-logon': typeof GestoresLogonRoute
  '/login': typeof LoginRoute
  '/rateios': typeof RateiosRouteWithChildren
  '/serasa': typeof SerasaRouteWithChildren
  '/usuarios-pcv': typeof UsuariosPcvRoute
  '/rateios/$id': typeof RateiosIdRoute
  '/rateios/novo': typeof RateiosNovoRoute
  '/serasa/divisao': typeof SerasaDivisaoRoute
  '/serasa/envio': typeof SerasaEnvioRoute
  '/serasa/processos': typeof SerasaProcessosRoute
  '/rateios/': typeof RateiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/gestores-logon': typeof GestoresLogonRoute
  '/login': typeof LoginRoute
  '/serasa': typeof SerasaRouteWithChildren
  '/usuarios-pcv': typeof UsuariosPcvRoute
  '/rateios/$id': typeof RateiosIdRoute
  '/rateios/novo': typeof RateiosNovoRoute
  '/serasa/divisao': typeof SerasaDivisaoRoute
  '/serasa/envio': typeof SerasaEnvioRoute
  '/serasa/processos': typeof SerasaProcessosRoute
  '/rateios': typeof RateiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/gestores-logon': typeof GestoresLogonRoute
  '/login': typeof LoginRoute
  '/rateios': typeof RateiosRouteWithChildren
  '/serasa': typeof SerasaRouteWithChildren
  '/usuarios-pcv': typeof UsuariosPcvRoute
  '/rateios/$id': typeof RateiosIdRoute
  '/rateios/novo': typeof RateiosNovoRoute
  '/serasa/divisao': typeof SerasaDivisaoRoute
  '/serasa/envio': typeof SerasaEnvioRoute
  '/serasa/processos': typeof SerasaProcessosRoute
  '/rateios/': typeof RateiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empresas'
    | '/gestores-logon'
    | '/login'
    | '/rateios'
    | '/serasa'
    | '/usuarios-pcv'
    | '/rateios/$id'
    | '/rateios/novo'
    | '/serasa/divisao'
    | '/serasa/envio'
    | '/serasa/processos'
    | '/rateios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empresas'
    | '/gestores-logon'
    | '/login'
    | '/serasa'
    | '/usuarios-pcv'
    | '/rateios/$id'
    | '/rateios/novo'
    | '/serasa/divisao'
    | '/serasa/envio'
    | '/serasa/processos'
    | '/rateios'
  id:
    | '__root__'
    | '/'
    | '/empresas'
    | '/gestores-logon'
    | '/login'
    | '/rateios'
    | '/serasa'
    | '/usuarios-pcv'
    | '/rateios/$id'
    | '/rateios/novo'
    | '/serasa/divisao'
    | '/serasa/envio'
    | '/serasa/processos'
    | '/rateios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpresasRoute: typeof EmpresasRoute
  GestoresLogonRoute: typeof GestoresLogonRoute
  LoginRoute: typeof LoginRoute
  RateiosRoute: typeof RateiosRouteWithChildren
  SerasaRoute: typeof SerasaRouteWithChildren
  UsuariosPcvRoute: typeof UsuariosPcvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios-pcv': {
      id: '/usuarios-pcv'
      path: '/usuarios-pcv'
      fullPath: '/usuarios-pcv'
      preLoaderRoute: typeof UsuariosPcvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serasa': {
      id: '/serasa'
      path: '/serasa'
      fullPath: '/serasa'
      preLoaderRoute: typeof SerasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rateios': {
      id: '/rateios'
      path: '/rateios'
      fullPath: '/rateios'
      preLoaderRoute: typeof RateiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestores-logon': {
      id: '/gestores-logon'
      path: '/gestores-logon'
      fullPath: '/gestores-logon'
      preLoaderRoute: typeof GestoresLogonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rateios/': {
      id: '/rateios/'
      path: '/'
      fullPath: '/rateios/'
      preLoaderRoute: typeof RateiosIndexRouteImport
      parentRoute: typeof RateiosRoute
    }
    '/serasa/processos': {
      id: '/serasa/processos'
      path: '/processos'
      fullPath: '/serasa/processos'
      preLoaderRoute: typeof SerasaProcessosRouteImport
      parentRoute: typeof SerasaRoute
    }
    '/serasa/envio': {
      id: '/serasa/envio'
      path: '/envio'
      fullPath: '/serasa/envio'
      preLoaderRoute: typeof SerasaEnvioRouteImport
      parentRoute: typeof SerasaRoute
    }
    '/serasa/divisao': {
      id: '/serasa/divisao'
      path: '/divisao'
      fullPath: '/serasa/divisao'
      preLoaderRoute: typeof SerasaDivisaoRouteImport
      parentRoute: typeof SerasaRoute
    }
    '/rateios/novo': {
      id: '/rateios/novo'
      path: '/novo'
      fullPath: '/rateios/novo'
      preLoaderRoute: typeof RateiosNovoRouteImport
      parentRoute: typeof RateiosRoute
    }
    '/rateios/$id': {
      id: '/rateios/$id'
      path: '/$id'
      fullPath: '/rateios/$id'
      preLoaderRoute: typeof RateiosIdRouteImport
      parentRoute: typeof RateiosRoute
    }
  }
}

interface RateiosRouteChildren {
  RateiosIdRoute: typeof RateiosIdRoute
  RateiosNovoRoute: typeof RateiosNovoRoute
  RateiosIndexRoute: typeof RateiosIndexRoute
}

const RateiosRouteChildren: RateiosRouteChildren = {
  RateiosIdRoute: RateiosIdRoute,
  RateiosNovoRoute: RateiosNovoRoute,
  RateiosIndexRoute: RateiosIndexRoute,
}

const RateiosRouteWithChildren =
  RateiosRoute._addFileChildren(RateiosRouteChildren)

interface SerasaRouteChildren {
  SerasaDivisaoRoute: typeof SerasaDivisaoRoute
  SerasaEnvioRoute: typeof SerasaEnvioRoute
  SerasaProcessosRoute: typeof SerasaProcessosRoute
}

const SerasaRouteChildren: SerasaRouteChildren = {
  SerasaDivisaoRoute: SerasaDivisaoRoute,
  SerasaEnvioRoute: SerasaEnvioRoute,
  SerasaProcessosRoute: SerasaProcessosRoute,
}

const SerasaRouteWithChildren =
  SerasaRoute._addFileChildren(SerasaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpresasRoute: EmpresasRoute,
  GestoresLogonRoute: GestoresLogonRoute,
  LoginRoute: LoginRoute,
  RateiosRoute: RateiosRouteWithChildren,
  SerasaRoute: SerasaRouteWithChildren,
  UsuariosPcvRoute: UsuariosPcvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
